services:
#  nginx:
#    image: nginx:latest
#    hostname: nginx
#    container_name: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./tg_app/web/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./tg_app/web/html:/usr/share/nginx/html

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis_01
    restart: on-failure
    ports:
      - "6379:6379"

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    hostname: rabbitmq
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
#      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq


#volumes:
#  rabbitmq-data: