"""add unique name for prize

Revision ID: 2d344d2d95d0
Revises: 9837ccf19f8c
Create Date: 2025-09-16 21:58:04.328681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d344d2d95d0'
down_revision: Union[str, Sequence[str], None] = '9837ccf19f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_prizes_name'), 'prizes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_prizes_name'), 'prizes', type_='unique')
    # ### end Alembic commands ###
