"""add .. for prize 

Revision ID: c5f7370f26ba
Revises: 2d344d2d95d0
Create Date: 2025-09-16 22:02:28.924326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f7370f26ba'
down_revision: Union[str, Sequence[str], None] = '2d344d2d95d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('check_quantity', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prizes', 'check_quantity')
    # ### end Alembic commands ###
