"""refactor for prize 

Revision ID: a26bfd940010
Revises: c5f7370f26ba
Create Date: 2025-09-19 22:45:37.986383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26bfd940010'
down_revision: Union[str, Sequence[str], None] = 'c5f7370f26ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('won_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'won_at')
    # ### end Alembic commands ###
